# COURSERA python code
# DEEP LEARNING
### Neural Networks and Deep learning
#### 2 Weeks - Vectorization

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic))+"ms")

c=0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic))+"ms")

# for loop의 경우가 300배 느리다는 것을 알 수 있다.
# 벡터화의 중요성!

250134.6341406066
Vectorized version:1.0297298431396484ms
250134.63414059702
For loop:557.2218894958496ms


#### 2 Weeks - Broadcasting in python

In [5]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [6]:
cal = A.sum(axis=0) 
# axis = 0 (열) 세로로 더하기 axis = 1 (행) 가로로 더하기
print(cal)

[ 59.  239.  155.4  76.9]


In [7]:
percentage = A/cal.reshape(1,4)
print(percentage)

[[0.94915254 0.         0.02831403 0.88426528]
 [0.02033898 0.43514644 0.33462033 0.10403121]
 [0.03050847 0.56485356 0.63706564 0.01170351]]


#### 2 Weeks - A note on python/numpy vectors

In [9]:
import numpy as np

a = np.random.randn(5)
print(a)

[0.86110671 1.49601902 0.14126547 0.50981686 0.06131514]


In [10]:
print(a.shape) # rank 1 array 되도록 사용하지 말기. (5,1) 사용하기.

(5,)


In [11]:
print(a.T)

[0.86110671 1.49601902 0.14126547 0.50981686 0.06131514]


In [12]:
print(np.dot(a,a.T))

3.263206380431947


### Improving Deep Neural Networks
#### 3 Weeks - TensorFlow

In [2]:
conda install tensorflow

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\yeongeunkim\Anaconda3

  added / updated specs:
    - tensorflow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _tflow_select-2.3.0        |              mkl           3 KB
    absl-py-0.11.0             |     pyhd3eb1b0_1         103 KB
    astor-0.8.1                |   py37haa95532_0          47 KB
    gast-0.4.0                 |             py_0          15 KB
    grpcio-1.16.1              |   py37h351948d_1         850 KB
    importlib-metadata-2.0.0   |             py_1          35 KB
    keras-applications-1.0.8   |             py_1          29 KB
    keras-preproces

In [3]:
import numpy as np
import tensorflow as tf

In [13]:
w = tf.Variable(0,dtype=tf.float32) 

In [18]:
w = tf.Variable(0,dtype=tf.float32) # w를 0으로 초기화
#cost = tf.add(tf.add(w**2,tf.multiply(-10,w)),25) # 비용함수 정의
cost = w**2 - 10*w + 25
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost) 
# trian이 러닝 알고리즘이 되도록 정의

# global variables 초기화
init = tf.global_variables_initializer()
session = tf.Session()
session.run(init) 
print(session.run(w)) #evaluative variable

0.0


In [19]:
session.run(train)
print(session.run(w))

0.099999994


In [20]:
for i in range(1000):
    session.run(train)
print(session.run(w))

4.9999886


In [25]:
coefficients = np.array([[1.],[-10.],[25.]])

w = tf.Variable(0,dtype = tf.float32) # w를 0으로 초기화
x = tf.placeholder(tf.float32,[3,1])
cost = x[0][0]*w**2 + x[1][0]*w + x[2][0] #(w-5)**2
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost) 
# trian이 러닝 알고리즘이 되도록 정의

# global variables 초기화
init = tf.global_variables_initializer()
session = tf.Session()
session.run(init) 
print(session.run(w)) #evaluative variable

0.0


In [26]:
session.run(train, feed_dict={x:coefficients})
print(session.run(w))

0.099999994


In [27]:
for i in range(1000):
    session.run(train, feed_dict={x:coefficients})
print(session.run(w))

4.9999886
